### ISSUE TITLE
Support working with ExtractTextPlugin

### ISSUE THREAD

**Issue by japboy** [quackes/webpack-encoding-plugin#3]
I currently use this encoding plugin and the webpack default ExtractTextPlugin. Somehow the extracted css cannot be encoded with this plugin.

Is there any way to solve this problem? Or is it possible to fix the plugin to support this use case?

Thanks in advance.

**Comment by quackes** [comment]
i have to look into that, i cant tell right now

**Comment by quackes** [comment]
ok my findings so far:
it seems, that my non ascii chars (german ÄÖÜ) where translated to unicode hex expressions, presumably by the style loader.
im testing with thre codepage iso-8859-1 (aka Latin-1)
so there where no special chars in css that differ from utf8 and iso-8859-1

which codepage/encoding are you using, and what is your exact error?
can you provide the essential code?

**Comment by japboy** [comment]
my use case is to encode from UTF-8 to Shift_JIS. and i also found that webpack build process somehow converts from non-ascii chars (ex in japanese `font-family: "メイリオ";`) to hex expressions (`font-family:\\30E1\30A4\30EA\30AA`). this conversion also occurs without this plugin.

is this helpful to solve this problem? thanks.

**Comment by quackes** [comment]
the problem is, that css-loader leaves the css file with the utf-8 hex expressions, so my plugin has nothing to encode, because the file is comliant to both utf-8 and (in your case) Shift_JIS, which is, from what i read, compliant to utf-8 in terms of the ascii chars.

here is an issue where someone describes the behavior we found:
https://github.com/webpack/css-loader/issues/317

i guess, that if css-loader would not do this conversion, that the webpack-encoding-plugin would work fine.
but imho its not the responsibility of the plugin to revert this conversion.

if its only the font, you are loading, maybe you could include the font in the css via base64 file url with @font-face, if thats an option.
